### ISSUE TITLE
Minimum python version

### ISSUE THREAD

**Issue by MaximilienNaveau** [machines-in-motion/breathing-cat#31]
The minimum python version of python3.8 is an issue for some people and I guess we should discuss briefly the minimum version problematic.

The code for the robot we use in machines-in-motion organisation is principaly made for ubuntu18.04/20.04 hence the minimum python requirement is python3.6.

@luator how complex would it be to downgrade this minimum python version?

**Comment by luator** [comment]
I did a quick test.  It seems the only things for which 3.8 is needed are
- `importlib.metadata` (used to get the package version in `__init__.py`).
- `typing.Literal`

At least the tests succeed on 3.7 if those two things are removed.  Both are nice to have but we could live without them if needed.  However, this only brings us down to 3.7 which doesn't really help.

For 3.6 some more work would be needed (the build setups of breathing cat and variconf currently depend on a newer setuptools version which is not available for 3.6).  Since 3.6 already reached end of life almost a year ago, I'm not sure if that's really worth the effort.  Wouldn't it be better to instead invest the time to upgrade from 18.04 to 20.04?  Do you know what would be missing there?  All the packages I am concerned with (everything in the ROBOT_FINGERS and SOLO projects) already work with 20.04.

Edit: I just saw that Ubuntu 18.04 also reaches EOL in April, so that might be another incentive to upgrade.

**Comment by MaximilienNaveau** [comment]
Ok fine, it would be nice to keep compatibility to lowest python version of the lowest LTS ubuntu version.

Right now I guess it's `Ubuntu20.04` hence `python3.8`
